name: GravityGun
main: net.apcat.gravitygun.GravityGun
version: 1.0
author: AgentK20
description: This GravityGun plugin was coded in a speed code series on the AgentK20 youtube channel! https://www.youtube.com/watch?v=4Il-CFTOLVs